baseURL = "https://ayman546525-boop.github.io/southern-website/blog/"
languageCode = "en-us"
title = "The Edge Feed | Southern IoT"
paginate = 9
relativeURLs = false
canonifyURLs = false

[params]
  description = "Precision insights into the industrial edge."
  author = "Southern IoT"
  siteRoot = "/southern-website/"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "dracula"
